### ISSUE TITLE
confused about implement of low-pass filter

### ISSUE THREAD

**Issue by HueCheng1021** [liqimai/Efficient-SSL#1]
hi, I am confused about some part of the code.
when smoothing type is rnm, the specific code is as follows
'''''''''''''''''
adj = normalize_adj(adj + sp.eye(adj.shape[0]), 'sym')
smoothor = sp.eye(n) * (1 - lam) + lam * adj
inflator = sp.eye(n) * (1 - mu) + mu * adj
step_transformor = smoothor * inflator
,where lam=1 and mu=0
''''''''''''''''''
so it can be inferred that the value of step_transfomor is adj*sp.eye(n). 
Does the step_transfomor is low-pass filter? According to the paper, shounldn't it be sp.eye(n)-adj?
I hope to receive your reply as soon as possible. Thank you!

**Comment by liqimai** [comment]
The frequency response is defined on the Laplacian, not adjacency matrix.
Here, the `step_transformer == adj == sp.eye(n) - Laplacian` is low pass as described in paper.
