### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by Serendipity-LC** [liqimai/Efficient-SSL#3]
你好，请问一下您给出的数据中  .x  .y  .tx  .ty  .allx  .ally  .graph  .index 分别存储的是什么？

**Comment by liqimai** [comment]
> Hello, what do files ".x .y .tx .ty .allx .ally .graph .index" store？

The data comes from kipf's repository https://github.com/tkipf/gcn, and originally provided by yang's repository https://github.com/kimiyoung/planetoid/tree/master/data. 

All of three papers, Kipf's, Yang's, and ours have dataset description, which may help you. Furthermore, the function 'load_data' in 'utils.py' gives the logic to process these files.
