### ISSUE TITLE
实验

### ISSUE THREAD

**Issue by Serendipity-LC** [liqimai/Efficient-SSL#4]
您好！这个代码是没有半监督回归任务的是吗？

**Comment by liqimai** [comment]
No, not include regression. Regression experiments rely on ADGPM's code [29].
https://github.com/cyvius96/adgpm

**Comment by Serendipity-LC** [comment]
论文中的实验是直接把https://github.com/cyvius96/adgpm里面的图卷积改为GLP和IGCN就可以了吗？
